### ISSUE TITLE
Filter non-CP problems in ;gimme

### ISSUE THREAD

**Issue by jacklee1792** [cheran-senthil/TLE#336] opened 2020-07-04 11:44 UTC
Calling ;gimme sometimes returns unconventional problems, such as:

![image](https://user-images.githubusercontent.com/43303581/86511766-26c96e00-bdca-11ea-86be-69e3eae86741.png)
![image](https://user-images.githubusercontent.com/43303581/86511768-2df07c00-bdca-11ea-90bc-de8e16ea0be4.png)

**Comment by algmyr** [comment] 2020-07-11 18:07
This is intended behavior for `;gimme`. Filtering was added to `;gitgud` et al because of the nature of the command (solve to move on, or skip later). With `;gimme` you can just request a new problem. If you would want this kind of behavior, feel free to make a PR and I'm happy to consider it. In the meantime I'll close this as WAI.

**Closed** 2020-07-11 18:09 UTC
Labels: working as intended
