### ISSUE TITLE
Unable to convert <username> to a server member

### ISSUE THREAD

**Issue by aseet-dhale** [cheran-senthil/TLE#406] opened 2020-10-29 09:34 UTC
`;handle list` gives
`No members with registered handles.`

Even though I have like 25+ members registered with the BOT. But when i use `handle get @<discord_username>` gives the expected output.

Below is a screenshot for the same:

`;handle list`
![Screenshot from 2020-10-29 14-51-19](https://user-images.githubusercontent.com/46392286/97549376-52fe9f80-19f6-11eb-89e0-4939b5617a74.png)

`;handle get @<discord_username>`
![Screenshot from 2020-10-29 14-53-01_1](https://user-images.githubusercontent.com/46392286/97550465-b6d59800-19f7-11eb-8535-7c7c26ed76ff.png)

**Comment by aryanc403** [comment] 2020-10-29 09:53
#393 is the root cause. It will be fixed along with it. For now, just downgrade you discord.py version to 1.3.x and close this.

**Comment by algmyr** [comment] 2020-10-29 10:18
Everything <1.5 should be fine, our instance runs 1.4.2 which is the latest release before 1.5. Also, if you are installing using poetry this shouldn't be an issue since we specify this version requirements in the project file (since about a week ago when we realized the breaking issues with 1.5).

**Comment by algmyr** [comment] 2020-10-29 10:20
But yeah, duplicate of #393.

**Closed by algmyr** 2020-10-29 10:20 UTC

**Comment by aryanc403** [comment] 2020-10-29 10:59
Downgrading does work now for me atleast. But still a duplicate issue.

**Comment by aseet-dhale** [comment] 2020-10-29 11:22
Yeah for me too. Also the discord.py was version _**1.3.x**_ **not 1.5**. Now i have updated to the version 1.4.2 but i may have to re-register my member now. Is there any fix.

**Comment by aryanc403** [comment] 2020-10-29 11:29
discord.py==1.5 changes the API gateway. New gateway asks to explicitly allow the bot to fetch all members list. Along with similar changes in the codebase, which we haven't done so far. 1.5 is definitely an issue until we make required changes in the codebase.

**Comment by aseet-dhale** [comment] 2020-10-29 11:32
Yeah sure, but i did not have 1.5. The version i had was 1.3.x(something) and now i updated it to 1.4.2 as it was supposed to. So is not having 1.5 is a issue?

**Comment by aryanc403** [comment] 2020-10-29 11:34
https://discordpy.readthedocs.io/en/latest/intents.html#intents-primer
